export const reducerCases = {
  TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
  TOGGLE_SIGNUP_MODAL: "TOGGLE_SIGNUP_MODAL",
  CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
  SET_USER: "SET_USER",
  SWITCH_MODE: "SWITCH_MODE",
  SET_GIG_DATA: "SET_GIG_DATA",
  HAS_USER_ORDERED_GIG: "HAS_USER_ORDERED_GIG",
  ADD_REVIEW: "ADD_REVIEW",
};
